name: website
on:
  push:
    branches:
      - main

jobs:
  website:
    name: Build pres for Computo
    if: "contains(github.event.head_commit.message, 'build')"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            mkdir _build
            cd latest/
            quarto render Computo.qmd
            mv Computo.html ../_build/index.html

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
